### ISSUE TITLE
hi, how can I got the doc of this lib.

### ISSUE THREAD

**Issue by hackrole** [Distrotech/pycups#1]
I would like to use this lib in my project. but the doc is so less. I cannot start anything now.
Is there anywhere I can got help, doc , example, google-group or other things.

**Comment by tanuj101** [comment]
@hackrole [this](http://nagyak.eastron.hu/doc/system-config-printer-libs-1.2.4/pycups-1.9.51/html/) this will help

**Comment by tanuj101** [comment]
if you still need it
